aws_region     = "eu-west-2"
state_bucket   = "kingchappers-terraform-state-bucket"
app_name       = "budget-app-v3-ai-edition"
environment    = "production"
auth0_audience = "https://dev-xf4mizgda1uv0xvb.uk.auth0.com/api/v2/"
